; PlatformIO Project Configuration File
; https://docs.platformio.org/page/projectconf.html

[common]
lib_deps      = https://github.com/CuriousScientist0/ADS1256.git
monitor_speed = 250000

;  AVR 

[env:nanoatmega328new]
platform  = atmelavr
board     = nanoatmega328new
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

[env:uno]
platform  = atmelavr
board     = uno
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

[env:mega2560]
platform  = atmelavr
board     = megaatmega2560
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

;  RP2040 

[env:rpipico]
platform  = https://github.com/maxgerhardt/platform-raspberrypi.git
board     = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

; Uncomment build_flags below to use SPI1 instead of SPI0 on RP2040:
; build_flags = -D USE_SPI1

;  STM32 

[env:blackpill_f411ce]
platform  = ststm32
board     = blackpill_f411ce
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

[env:bluepill_f103c8]
platform  = ststm32
board     = bluepill_f103c8
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

; Uncomment build_flags below to use SPI2 instead of SPI1 on STM32:
; build_flags = -D USE_SPI2

;  Teensy 

[env:teensy40]
platform  = teensy
board     = teensy40
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

[env:teensy41]
platform  = teensy
board     = teensy41
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

; Uncomment build_flags below to use SPI1 or SPI2 on Teensy:
; build_flags = -D USE_SPI1
; build_flags = -D USE_SPI2

;  ESP32 

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

[env:esp32s3]
platform  = espressif32
board     = esp32-s3-devkitc-1
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

[env:esp32c3]
platform  = espressif32
board     = esp32-c3-devkitm-1
framework = arduino
monitor_speed = ${common.monitor_speed}
lib_deps  = ${common.lib_deps}

; Uncomment build_flags below to use HSPI instead of VSPI on ESP32:
; build_flags = -D USE_HSPI